# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crv < Formula
  desc "Coverage report viewer for terminals"
  homepage "https://github.com/izuno4t/coverage-report-viewer-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/izuno4t/coverage-report-viewer-cli/releases/download/v0.1.0/crv_0.1.0_darwin_x86_64.tar.gz"
      sha256 "5e77cab26c9d566358464b56767ad9d16d1c1cd2a29dbd3b1e0dc17f72eb44c7"

      define_method(:install) do
        bin.install "crv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/izuno4t/coverage-report-viewer-cli/releases/download/v0.1.0/crv_0.1.0_darwin_arm64.tar.gz"
      sha256 "d9c07ed1e8a41c469065101e58349976435a423aa3bf5e3a320ac9778fef0583"

      define_method(:install) do
        bin.install "crv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/izuno4t/coverage-report-viewer-cli/releases/download/v0.1.0/crv_0.1.0_linux_x86_64.tar.gz"
      sha256 "298b8aa4245ea45b62ec3e28986f8858d42d03b5be858c333cd66c3a100cbce3"
      define_method(:install) do
        bin.install "crv"
      end
    end
  end

  test do
    system "#{bin}/crv", "--version"
  end
end
